
interface _GlobalComponents {
      'Claim': typeof import("../components/Claim/index.vue")['default']
    'DashboardAppeal': typeof import("../components/Dashboard/Appeal/index.vue")['default']
    'DashboardClaimModalLoadingModal': typeof import("../components/Dashboard/ClaimModal/LoadingModal.vue")['default']
    'DashboardClaimModal': typeof import("../components/Dashboard/ClaimModal/index.vue")['default']
    'DashboardDailyClaim': typeof import("../components/Dashboard/DailyClaim/index.vue")['default']
    'DashboardGovernance': typeof import("../components/Dashboard/Governance/index.vue")['default']
    'DashboardHeader': typeof import("../components/Dashboard/Header/index.vue")['default']
    'DashboardLeaderboard': typeof import("../components/Dashboard/Leaderboard/index.vue")['default']
    'DashboardMintLoadingModal': typeof import("../components/Dashboard/Mint/LoadingModal.vue")['default']
    'DashboardMint': typeof import("../components/Dashboard/Mint/index.vue")['default']
    'DashboardNominateNewModal': typeof import("../components/Dashboard/Nominate/NewModal.vue")['default']
    'DashboardNominate': typeof import("../components/Dashboard/Nominate/index.vue")['default']
    'DashboardProfileModal': typeof import("../components/Dashboard/ProfileModal/index.vue")['default']
    'DashboardProposalMetric': typeof import("../components/Dashboard/Proposal/Metric.vue")['default']
    'DashboardProposalProgressBar': typeof import("../components/Dashboard/Proposal/ProgressBar.vue")['default']
    'DashboardProposalStakeCard': typeof import("../components/Dashboard/Proposal/StakeCard.vue")['default']
    'DashboardProposal': typeof import("../components/Dashboard/Proposal/index.vue")['default']
    'DashboardReferral': typeof import("../components/Dashboard/Referral/index.vue")['default']
    'DashboardStake': typeof import("../components/Dashboard/Stake/index.vue")['default']
    'DashboardVoting': typeof import("../components/Dashboard/Voting/index.vue")['default']
    'Dashboard': typeof import("../components/Dashboard/index.vue")['default']
    'Footer': typeof import("../components/Footer/index.vue")['default']
    'Header': typeof import("../components/Header/index.vue")['default']
    'Home': typeof import("../components/Home/index.vue")['default']
    'Modal': typeof import("../components/Modal/index.vue")['default']
    'Newsletter': typeof import("../components/Newsletter/index.vue")['default']
    'Signup': typeof import("../components/Signup/index.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'Icon': typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
      'LazyClaim': typeof import("../components/Claim/index.vue")['default']
    'LazyDashboardAppeal': typeof import("../components/Dashboard/Appeal/index.vue")['default']
    'LazyDashboardClaimModalLoadingModal': typeof import("../components/Dashboard/ClaimModal/LoadingModal.vue")['default']
    'LazyDashboardClaimModal': typeof import("../components/Dashboard/ClaimModal/index.vue")['default']
    'LazyDashboardDailyClaim': typeof import("../components/Dashboard/DailyClaim/index.vue")['default']
    'LazyDashboardGovernance': typeof import("../components/Dashboard/Governance/index.vue")['default']
    'LazyDashboardHeader': typeof import("../components/Dashboard/Header/index.vue")['default']
    'LazyDashboardLeaderboard': typeof import("../components/Dashboard/Leaderboard/index.vue")['default']
    'LazyDashboardMintLoadingModal': typeof import("../components/Dashboard/Mint/LoadingModal.vue")['default']
    'LazyDashboardMint': typeof import("../components/Dashboard/Mint/index.vue")['default']
    'LazyDashboardNominateNewModal': typeof import("../components/Dashboard/Nominate/NewModal.vue")['default']
    'LazyDashboardNominate': typeof import("../components/Dashboard/Nominate/index.vue")['default']
    'LazyDashboardProfileModal': typeof import("../components/Dashboard/ProfileModal/index.vue")['default']
    'LazyDashboardProposalMetric': typeof import("../components/Dashboard/Proposal/Metric.vue")['default']
    'LazyDashboardProposalProgressBar': typeof import("../components/Dashboard/Proposal/ProgressBar.vue")['default']
    'LazyDashboardProposalStakeCard': typeof import("../components/Dashboard/Proposal/StakeCard.vue")['default']
    'LazyDashboardProposal': typeof import("../components/Dashboard/Proposal/index.vue")['default']
    'LazyDashboardReferral': typeof import("../components/Dashboard/Referral/index.vue")['default']
    'LazyDashboardStake': typeof import("../components/Dashboard/Stake/index.vue")['default']
    'LazyDashboardVoting': typeof import("../components/Dashboard/Voting/index.vue")['default']
    'LazyDashboard': typeof import("../components/Dashboard/index.vue")['default']
    'LazyFooter': typeof import("../components/Footer/index.vue")['default']
    'LazyHeader': typeof import("../components/Header/index.vue")['default']
    'LazyHome': typeof import("../components/Home/index.vue")['default']
    'LazyModal': typeof import("../components/Modal/index.vue")['default']
    'LazyNewsletter': typeof import("../components/Newsletter/index.vue")['default']
    'LazySignup': typeof import("../components/Signup/index.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyIcon': typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const Claim: typeof import("../components/Claim/index.vue")['default']
export const DashboardAppeal: typeof import("../components/Dashboard/Appeal/index.vue")['default']
export const DashboardClaimModalLoadingModal: typeof import("../components/Dashboard/ClaimModal/LoadingModal.vue")['default']
export const DashboardClaimModal: typeof import("../components/Dashboard/ClaimModal/index.vue")['default']
export const DashboardDailyClaim: typeof import("../components/Dashboard/DailyClaim/index.vue")['default']
export const DashboardGovernance: typeof import("../components/Dashboard/Governance/index.vue")['default']
export const DashboardHeader: typeof import("../components/Dashboard/Header/index.vue")['default']
export const DashboardLeaderboard: typeof import("../components/Dashboard/Leaderboard/index.vue")['default']
export const DashboardMintLoadingModal: typeof import("../components/Dashboard/Mint/LoadingModal.vue")['default']
export const DashboardMint: typeof import("../components/Dashboard/Mint/index.vue")['default']
export const DashboardNominateNewModal: typeof import("../components/Dashboard/Nominate/NewModal.vue")['default']
export const DashboardNominate: typeof import("../components/Dashboard/Nominate/index.vue")['default']
export const DashboardProfileModal: typeof import("../components/Dashboard/ProfileModal/index.vue")['default']
export const DashboardProposalMetric: typeof import("../components/Dashboard/Proposal/Metric.vue")['default']
export const DashboardProposalProgressBar: typeof import("../components/Dashboard/Proposal/ProgressBar.vue")['default']
export const DashboardProposalStakeCard: typeof import("../components/Dashboard/Proposal/StakeCard.vue")['default']
export const DashboardProposal: typeof import("../components/Dashboard/Proposal/index.vue")['default']
export const DashboardReferral: typeof import("../components/Dashboard/Referral/index.vue")['default']
export const DashboardStake: typeof import("../components/Dashboard/Stake/index.vue")['default']
export const DashboardVoting: typeof import("../components/Dashboard/Voting/index.vue")['default']
export const Dashboard: typeof import("../components/Dashboard/index.vue")['default']
export const Footer: typeof import("../components/Footer/index.vue")['default']
export const Header: typeof import("../components/Header/index.vue")['default']
export const Home: typeof import("../components/Home/index.vue")['default']
export const Modal: typeof import("../components/Modal/index.vue")['default']
export const Newsletter: typeof import("../components/Newsletter/index.vue")['default']
export const Signup: typeof import("../components/Signup/index.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const Icon: typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyClaim: typeof import("../components/Claim/index.vue")['default']
export const LazyDashboardAppeal: typeof import("../components/Dashboard/Appeal/index.vue")['default']
export const LazyDashboardClaimModalLoadingModal: typeof import("../components/Dashboard/ClaimModal/LoadingModal.vue")['default']
export const LazyDashboardClaimModal: typeof import("../components/Dashboard/ClaimModal/index.vue")['default']
export const LazyDashboardDailyClaim: typeof import("../components/Dashboard/DailyClaim/index.vue")['default']
export const LazyDashboardGovernance: typeof import("../components/Dashboard/Governance/index.vue")['default']
export const LazyDashboardHeader: typeof import("../components/Dashboard/Header/index.vue")['default']
export const LazyDashboardLeaderboard: typeof import("../components/Dashboard/Leaderboard/index.vue")['default']
export const LazyDashboardMintLoadingModal: typeof import("../components/Dashboard/Mint/LoadingModal.vue")['default']
export const LazyDashboardMint: typeof import("../components/Dashboard/Mint/index.vue")['default']
export const LazyDashboardNominateNewModal: typeof import("../components/Dashboard/Nominate/NewModal.vue")['default']
export const LazyDashboardNominate: typeof import("../components/Dashboard/Nominate/index.vue")['default']
export const LazyDashboardProfileModal: typeof import("../components/Dashboard/ProfileModal/index.vue")['default']
export const LazyDashboardProposalMetric: typeof import("../components/Dashboard/Proposal/Metric.vue")['default']
export const LazyDashboardProposalProgressBar: typeof import("../components/Dashboard/Proposal/ProgressBar.vue")['default']
export const LazyDashboardProposalStakeCard: typeof import("../components/Dashboard/Proposal/StakeCard.vue")['default']
export const LazyDashboardProposal: typeof import("../components/Dashboard/Proposal/index.vue")['default']
export const LazyDashboardReferral: typeof import("../components/Dashboard/Referral/index.vue")['default']
export const LazyDashboardStake: typeof import("../components/Dashboard/Stake/index.vue")['default']
export const LazyDashboardVoting: typeof import("../components/Dashboard/Voting/index.vue")['default']
export const LazyDashboard: typeof import("../components/Dashboard/index.vue")['default']
export const LazyFooter: typeof import("../components/Footer/index.vue")['default']
export const LazyHeader: typeof import("../components/Header/index.vue")['default']
export const LazyHome: typeof import("../components/Home/index.vue")['default']
export const LazyModal: typeof import("../components/Modal/index.vue")['default']
export const LazyNewsletter: typeof import("../components/Newsletter/index.vue")['default']
export const LazySignup: typeof import("../components/Signup/index.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyIcon: typeof import("../node_modules/nuxt-icon/dist/runtime/Icon.vue")['default']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']

export const componentNames: string[]
