// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 1/16/2026, 6:53:49 PM
const configMerger = require("/Users/icon/ico/uhtairdrop/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.mjs");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/icon/ico/uhtairdrop/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/icon/ico/uhtairdrop/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/icon/ico/uhtairdrop/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/icon/ico/uhtairdrop/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/icon/ico/uhtairdrop/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/icon/ico/uhtairdrop/plugins/**/*.{js,ts,mjs}","/Users/icon/ico/uhtairdrop/composables/**/*.{js,ts,mjs}","/Users/icon/ico/uhtairdrop/utils/**/*.{js,ts,mjs}","/Users/icon/ico/uhtairdrop/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/icon/ico/uhtairdrop/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/icon/ico/uhtairdrop/app.config.{js,ts,mjs}"] }));

module.exports = config
